name: Update Profile README with Activity

on:
  schedule:
    - cron: '0 */6 * * *'  # every 6 hours
  workflow_dispatch:       # allow manual trigger

jobs:
  update-readme:
    name: Update Recent Activity in README
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update README with recent activity
        uses: Readme-Workflows/recent-activity@main
        with:
          GH_USERNAME: saileshkumar16
